"""add reading corrections

Revision ID: 2b5fb43afb91
Revises: 8b6b593faca3
Create Date: 2026-08-29 16:20:50.359395
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2b5fb43afb91"
down_revision: str | None = "8b6b593faca3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reading_correction",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("reading_id", sa.Uuid(), nullable=False),
        sa.Column(
            "previous_energy_kwh", sa.Numeric(precision=18, scale=6), nullable=False
        ),
        sa.Column(
            "proposed_energy_kwh", sa.Numeric(precision=18, scale=6), nullable=False
        ),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("proposed_by_credential_id", sa.Uuid(), nullable=False),
        sa.Column("source_submission_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("proposed", "approved", "rejected", name="correction_status"),
            nullable=False,
        ),
        sa.Column("proposed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by_account_id", sa.Uuid(), nullable=True),
        sa.Column("decision_reason", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["decided_by_account_id"],
            ["user_account.id"],
            name=op.f("fk_reading_correction_decided_by_account_id_user_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_credential_id"],
            ["meter_credential.id"],
            name=op.f(
                "fk_reading_correction_proposed_by_credential_id_meter_credential"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reading_id"],
            ["meter_hourly_reading.id"],
            name=op.f("fk_reading_correction_reading_id_meter_hourly_reading"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_submission_id"],
            ["reading_submission.id"],
            name=op.f("fk_reading_correction_source_submission_id_reading_submission"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reading_correction")),
        sa.UniqueConstraint(
            "reading_id",
            "proposed_energy_kwh",
            name="uq_reading_correction_reading_proposed_energy",
        ),
    )
    op.create_index(
        op.f("ix_reading_correction_reading_id"),
        "reading_correction",
        ["reading_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_correction_university_id"),
        "reading_correction",
        ["university_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_reading_correction_university_id"), table_name="reading_correction"
    )
    op.drop_index(
        op.f("ix_reading_correction_reading_id"), table_name="reading_correction"
    )
    op.drop_table("reading_correction")
    postgresql.ENUM(name="correction_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
