"""add meter credentials

Revision ID: 78aac89fe4b7
Revises: 86b023d25a5a
Create Date: 2026-08-29 15:56:56.525840
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "78aac89fe4b7"
down_revision: str | None = "86b023d25a5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meter_authentication_attempt",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("meter_id", sa.Uuid(), nullable=False),
        sa.Column("credential_id", sa.Uuid(), nullable=True),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=40), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meter_authentication_attempt")),
    )
    op.create_index(
        op.f("ix_meter_authentication_attempt_attempted_at"),
        "meter_authentication_attempt",
        ["attempted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meter_authentication_attempt_meter_id"),
        "meter_authentication_attempt",
        ["meter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meter_authentication_attempt_university_id"),
        "meter_authentication_attempt",
        ["university_id"],
        unique=False,
    )
    op.create_table(
        "meter_credential",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("meter_id", sa.Uuid(), nullable=False),
        sa.Column("secret_hash", sa.LargeBinary(), nullable=False),
        sa.Column("salt", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotated_from_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["meter_id", "university_id"],
            ["meter.id", "meter.university_id"],
            name=op.f("fk_meter_credential_meter_id_meter"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meter_credential")),
    )
    op.create_index(
        op.f("ix_meter_credential_meter_id"),
        "meter_credential",
        ["meter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meter_credential_university_id"),
        "meter_credential",
        ["university_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_meter_credential_university_id"), table_name="meter_credential"
    )
    op.drop_index(op.f("ix_meter_credential_meter_id"), table_name="meter_credential")
    op.drop_table("meter_credential")
    op.drop_index(
        op.f("ix_meter_authentication_attempt_university_id"),
        table_name="meter_authentication_attempt",
    )
    op.drop_index(
        op.f("ix_meter_authentication_attempt_meter_id"),
        table_name="meter_authentication_attempt",
    )
    op.drop_index(
        op.f("ix_meter_authentication_attempt_attempted_at"),
        table_name="meter_authentication_attempt",
    )
    op.drop_table("meter_authentication_attempt")
    # ### end Alembic commands ###
