"""add dorm topology

Revision ID: 86b023d25a5a
Revises: 20260829_0001
Create Date: 2026-08-29 15:52:28.510050
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "86b023d25a5a"
down_revision: str | None = "20260829_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "building",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["university.id"],
            name=op.f("fk_building_university_id_university"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_building")),
        sa.UniqueConstraint("id", "university_id", name=op.f("uq_building_id")),
    )
    op.create_index(
        op.f("ix_building_university_id"), "building", ["university_id"], unique=False
    )
    op.create_table(
        "fuse_box",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("external_reference", sa.String(length=200), nullable=False),
        sa.Column(
            "state",
            sa.Enum("active", "inactive", name="fuse_box_operational_state"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["university.id"],
            name=op.f("fk_fuse_box_university_id_university"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fuse_box")),
        sa.UniqueConstraint("id", "university_id", name=op.f("uq_fuse_box_id")),
        sa.UniqueConstraint(
            "university_id",
            "external_reference",
            name=op.f("uq_fuse_box_university_id"),
        ),
    )
    op.create_index(
        op.f("ix_fuse_box_university_id"), "fuse_box", ["university_id"], unique=False
    )
    op.create_table(
        "meter",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("external_reference", sa.String(length=200), nullable=False),
        sa.Column(
            "state",
            sa.Enum("active", "inactive", name="meter_operational_state"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["university.id"],
            name=op.f("fk_meter_university_id_university"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meter")),
        sa.UniqueConstraint("id", "university_id", name=op.f("uq_meter_id")),
        sa.UniqueConstraint(
            "university_id", "external_reference", name=op.f("uq_meter_university_id")
        ),
    )
    op.create_index(
        op.f("ix_meter_university_id"), "meter", ["university_id"], unique=False
    )
    op.create_table(
        "apartment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("building_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["building_id", "university_id"],
            ["building.id", "building.university_id"],
            name=op.f("fk_apartment_building_id_building"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_apartment")),
        sa.UniqueConstraint(
            "building_id", "label", name=op.f("uq_apartment_building_id")
        ),
        sa.UniqueConstraint("id", "university_id", name=op.f("uq_apartment_id")),
    )
    op.create_index(
        op.f("ix_apartment_building_id"), "apartment", ["building_id"], unique=False
    )
    op.create_index(
        op.f("ix_apartment_university_id"), "apartment", ["university_id"], unique=False
    )
    op.create_table(
        "meter_fuse_box_assignment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("meter_id", sa.Uuid(), nullable=False),
        sa.Column("fuse_box_id", sa.Uuid(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_until", sa.DateTime(timezone=True), nullable=True),
        postgresql.ExcludeConstraint(
            (sa.column("meter_id"), "="),
            (sa.text("tstzrange(effective_from, effective_until, '[)')"), "&&"),
            using="gist",
            name="ex_meter_assignment_no_overlap",
        ),
        sa.CheckConstraint(
            "effective_until IS NULL OR effective_until > effective_from",
            name=op.f("ck_meter_fuse_box_assignment_positive_effective_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["fuse_box_id", "university_id"],
            ["fuse_box.id", "fuse_box.university_id"],
            name=op.f("fk_meter_fuse_box_assignment_fuse_box_id_fuse_box"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["meter_id", "university_id"],
            ["meter.id", "meter.university_id"],
            name=op.f("fk_meter_fuse_box_assignment_meter_id_meter"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meter_fuse_box_assignment")),
    )
    op.create_index(
        op.f("ix_meter_fuse_box_assignment_fuse_box_id"),
        "meter_fuse_box_assignment",
        ["fuse_box_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meter_fuse_box_assignment_meter_id"),
        "meter_fuse_box_assignment",
        ["meter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meter_fuse_box_assignment_university_id"),
        "meter_fuse_box_assignment",
        ["university_id"],
        unique=False,
    )
    op.create_table(
        "fuse_box_apartment_assignment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("fuse_box_id", sa.Uuid(), nullable=False),
        sa.Column("apartment_id", sa.Uuid(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_until", sa.DateTime(timezone=True), nullable=True),
        postgresql.ExcludeConstraint(
            (sa.column("fuse_box_id"), "="),
            (sa.text("tstzrange(effective_from, effective_until, '[)')"), "&&"),
            using="gist",
            name="ex_fuse_box_assignment_no_overlap",
        ),
        sa.CheckConstraint(
            "effective_until IS NULL OR effective_until > effective_from",
            name=op.f("ck_fuse_box_apartment_assignment_positive_effective_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["apartment_id", "university_id"],
            ["apartment.id", "apartment.university_id"],
            name=op.f("fk_fuse_box_apartment_assignment_apartment_id_apartment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fuse_box_id", "university_id"],
            ["fuse_box.id", "fuse_box.university_id"],
            name=op.f("fk_fuse_box_apartment_assignment_fuse_box_id_fuse_box"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fuse_box_apartment_assignment")),
    )
    op.create_index(
        op.f("ix_fuse_box_apartment_assignment_apartment_id"),
        "fuse_box_apartment_assignment",
        ["apartment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fuse_box_apartment_assignment_fuse_box_id"),
        "fuse_box_apartment_assignment",
        ["fuse_box_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fuse_box_apartment_assignment_university_id"),
        "fuse_box_apartment_assignment",
        ["university_id"],
        unique=False,
    )
    op.create_table(
        "room",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("apartment_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["apartment_id", "university_id"],
            ["apartment.id", "apartment.university_id"],
            name=op.f("fk_room_apartment_id_apartment"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room")),
        sa.UniqueConstraint("apartment_id", "label", name=op.f("uq_room_apartment_id")),
    )
    op.create_index(
        op.f("ix_room_apartment_id"), "room", ["apartment_id"], unique=False
    )
    op.create_index(
        op.f("ix_room_university_id"), "room", ["university_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_room_university_id"), table_name="room")
    op.drop_index(op.f("ix_room_apartment_id"), table_name="room")
    op.drop_table("room")
    op.drop_index(
        op.f("ix_fuse_box_apartment_assignment_university_id"),
        table_name="fuse_box_apartment_assignment",
    )
    op.drop_index(
        op.f("ix_fuse_box_apartment_assignment_fuse_box_id"),
        table_name="fuse_box_apartment_assignment",
    )
    op.drop_index(
        op.f("ix_fuse_box_apartment_assignment_apartment_id"),
        table_name="fuse_box_apartment_assignment",
    )
    op.drop_table("fuse_box_apartment_assignment")
    op.drop_index(
        op.f("ix_meter_fuse_box_assignment_university_id"),
        table_name="meter_fuse_box_assignment",
    )
    op.drop_index(
        op.f("ix_meter_fuse_box_assignment_meter_id"),
        table_name="meter_fuse_box_assignment",
    )
    op.drop_index(
        op.f("ix_meter_fuse_box_assignment_fuse_box_id"),
        table_name="meter_fuse_box_assignment",
    )
    op.drop_table("meter_fuse_box_assignment")
    op.drop_index(op.f("ix_apartment_university_id"), table_name="apartment")
    op.drop_index(op.f("ix_apartment_building_id"), table_name="apartment")
    op.drop_table("apartment")
    op.drop_index(op.f("ix_meter_university_id"), table_name="meter")
    op.drop_table("meter")
    op.drop_index(op.f("ix_fuse_box_university_id"), table_name="fuse_box")
    op.drop_table("fuse_box")
    op.drop_index(op.f("ix_building_university_id"), table_name="building")
    op.drop_table("building")
    bind = op.get_bind()
    for enum_name in ("meter_operational_state", "fuse_box_operational_state"):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
