"""add hourly ingestion

Revision ID: 8b6b593faca3
Revises: 78aac89fe4b7
Create Date: 2026-08-29 16:00:49.262638
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8b6b593faca3"
down_revision: str | None = "78aac89fe4b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reading_submission",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("meter_id", sa.Uuid(), nullable=False),
        sa.Column("credential_id", sa.Uuid(), nullable=False),
        sa.Column("correlation_id", sa.String(length=100), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("accepted_count", sa.Integer(), nullable=False),
        sa.Column("duplicate_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["meter_credential.id"],
            name=op.f("fk_reading_submission_credential_id_meter_credential"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reading_submission")),
    )
    op.create_index(
        op.f("ix_reading_submission_meter_id"),
        "reading_submission",
        ["meter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_submission_university_id"),
        "reading_submission",
        ["university_id"],
        unique=False,
    )
    op.create_table(
        "meter_hourly_reading",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("meter_id", sa.Uuid(), nullable=False),
        sa.Column("hour_start_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("energy_kwh", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("accepted", "quarantined", "rejected", name="reading_status"),
            nullable=False,
        ),
        sa.Column("credential_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["meter_credential.id"],
            name=op.f("fk_meter_hourly_reading_credential_id_meter_credential"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["meter_id", "university_id"],
            ["meter.id", "meter.university_id"],
            name=op.f("fk_meter_hourly_reading_meter_id_meter"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["reading_submission.id"],
            name=op.f("fk_meter_hourly_reading_submission_id_reading_submission"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meter_hourly_reading")),
        sa.UniqueConstraint(
            "meter_id", "hour_start_utc", name="uq_meter_hourly_reading_meter_hour"
        ),
    )
    op.create_index(
        op.f("ix_meter_hourly_reading_hour_start_utc"),
        "meter_hourly_reading",
        ["hour_start_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meter_hourly_reading_meter_id"),
        "meter_hourly_reading",
        ["meter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meter_hourly_reading_university_id"),
        "meter_hourly_reading",
        ["university_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_meter_hourly_reading_university_id"), table_name="meter_hourly_reading"
    )
    op.drop_index(
        op.f("ix_meter_hourly_reading_meter_id"), table_name="meter_hourly_reading"
    )
    op.drop_index(
        op.f("ix_meter_hourly_reading_hour_start_utc"),
        table_name="meter_hourly_reading",
    )
    op.drop_table("meter_hourly_reading")
    op.drop_index(
        op.f("ix_reading_submission_university_id"), table_name="reading_submission"
    )
    op.drop_index(
        op.f("ix_reading_submission_meter_id"), table_name="reading_submission"
    )
    op.drop_table("reading_submission")
    postgresql.ENUM(name="reading_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
